name: "project beta automations"
description: 'GitHub beta projects status field automation for Issues and Pull Requests'
inputs:
  github_token:
    description: 'Permission token that grants permission to the GitHub API..'
    required: true
    default: ""
  organization:
    description: 'Organization the project is stored in'
    required: true
    default: ""
  project_id:
    description: 'Project ID owned by the organization'
    required: true
    default: ""
  resource_node_id:
    description: 'Defines the global node ID of the GitHub issue or pull request'
    required: true
    default: ""
  status_value:
    description: 'Specifies the destination card to which the issue or pull request should be moved. The value must be of type string. Example: "Todo"'
    required: true
    default: ""
runs:
  using: "composite"
  steps:
    - name: "Execute automation"
      env:
        GITHUB_TOKEN: ${{ env.github_token }}
      shell: bash
      run: "./entrypoint.sh ${{ env.organization }} ${{ env.project_id }} ${{ env.resource_node_id }} ${{ env.status_value }}"
