name: feature request
description: Create a report to help us improve
title: "[ FEATURE REQUEST ]: "
labels:
  - feature request
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request report!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    id: related-to-a-problem
    attributes:
      label: Is your feature request related to a problem? Please describe
      description: A clear and concise description of what the problem is.
    validations:
      required: true
  - type: textarea
    id: solution-youd-like-to-see
    attributes:
      label: "Describe the solution you'd like:"
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional context:"
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false